# Generated by Django 4.1 on 2022-08-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_usernames',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('id_type', models.CharField(max_length=100, null=True)),
                ('id_value', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='m_userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('location_city', models.CharField(max_length=100, null=True)),
                ('location_state', models.CharField(max_length=100, null=True)),
                ('loation_country', models.CharField(max_length=100, null=True)),
                ('location_postcode', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('registered_date', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('cell', models.CharField(max_length=100, null=True)),
                ('picture', models.CharField(max_length=200, null=True)),
                ('nat', models.CharField(max_length=100, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_listing.m_usernames')),
            ],
        ),
    ]
